// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxcustajfzeqibnkjthp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94Y3VzdGFqZnplcWlibmtqdGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk0MzMzODEsImV4cCI6MjA4NTAwOTM4MX0.lyBeIVup_PBw4goIgt82C8O3I2eeDVVXTodx1JgLprU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});