// Gamification domain enums — shared across streak, mission, wallet,
// and NBA mechanics.

/// Status of a user's commute streak.
enum StreakStatus {
  active('active', 'نشط', 'Active'),
  grace('grace', 'فترة سماح', 'Grace Period'),
  broken('broken', 'منقطع', 'Broken'),
  recovered('recovered', 'مُستعاد', 'Recovered');

  const StreakStatus(this.key, this.labelAr, this.labelEn);
  final String key;
  final String labelAr;
  final String labelEn;

  String label({required bool isRtl}) => isRtl ? labelAr : labelEn;

  static StreakStatus fromString(String value) =>
      StreakStatus.values.firstWhere(
        (e) => e.key == value,
        orElse: () => StreakStatus.broken,
      );
}

/// Lifecycle status of a weekly mission.
/// Values match the DB CHECK constraint:
///   ('active', 'completed', 'expired', 'cancelled')
enum MissionStatus {
  active('active', 'نشط', 'Active'),
  completed('completed', 'مكتمل', 'Completed'),
  expired('expired', 'منتهي', 'Expired'),
  cancelled('cancelled', 'ملغى', 'Cancelled');

  const MissionStatus(this.key, this.labelAr, this.labelEn);
  final String key;
  final String labelAr;
  final String labelEn;

  String label({required bool isRtl}) => isRtl ? labelAr : labelEn;

  static MissionStatus fromString(String value) =>
      MissionStatus.values.firstWhere(
        (e) => e.key == value,
        orElse: () => MissionStatus.active,
      );
}

/// Category of a mission objective.
enum MissionCategory {
  commute('commute', 'تنقل', 'Commute'),
  social('social', 'اجتماعي', 'Social'),
  safety('safety', 'أمان', 'Safety'),
  general('general', 'عام', 'General');

  const MissionCategory(this.key, this.labelAr, this.labelEn);
  final String key;
  final String labelAr;
  final String labelEn;

  String label({required bool isRtl}) => isRtl ? labelAr : labelEn;

  static MissionCategory fromString(String value) =>
      MissionCategory.values.firstWhere(
        (e) => e.key == value,
        orElse: () => MissionCategory.general,
      );
}

/// Wallet value state for a reward unit.
enum WalletValueState {
  earned('earned', 'مكتسب', 'Earned'),
  unlocked('unlocked', 'مفتوح', 'Unlocked'),
  pending('pending', 'معلق', 'Pending'),
  redeemed('redeemed', 'مستبدل', 'Redeemed');

  const WalletValueState(this.key, this.labelAr, this.labelEn);
  final String key;
  final String labelAr;
  final String labelEn;

  String label({required bool isRtl}) => isRtl ? labelAr : labelEn;

  static WalletValueState fromString(String value) =>
      WalletValueState.values.firstWhere(
        (e) => e.key == value,
        orElse: () => WalletValueState.pending,
      );
}

/// Type of user-facing next-best-action recommendation.
enum ActionType {
  // Gamification-driven types (generated by get_next_action edge function)
  recoverStreak('recover_streak', 'استعادة السلسلة', 'Recover Streak'),
  completeMission('complete_mission', 'أكمل المهمة', 'Complete Mission'),
  startStreak('start_streak', 'ابدأ سلسلة', 'Start a Streak'),
  // Profile / engagement types
  takeRide('take_ride', 'خذ رحلة', 'Take a Ride'),
  completeProfile('complete_profile', 'أكمل ملفك', 'Complete Profile'),
  inviteFriend('invite_friend', 'ادعُ صديق', 'Invite a Friend'),
  ratePastRide('rate_past_ride', 'قيّم رحلة', 'Rate a Past Ride'),
  joinCommunity('join_community', 'انضم لمجتمع', 'Join a Community');

  const ActionType(this.key, this.labelAr, this.labelEn);
  final String key;
  final String labelAr;
  final String labelEn;

  String label({required bool isRtl}) => isRtl ? labelAr : labelEn;

  static ActionType fromString(String value) => ActionType.values.firstWhere(
        (e) => e.key == value,
        orElse: () => ActionType.takeRide,
      );
}
